[package]
name = "authd"
version = "0.1.0"
authors = ["Karsten Jeschkies <k@jeschkies.xyz>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
log = "0.4"
jsonwebtoken = "6"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
